spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/dictionary_db?sslMode=VERIFY_IDENTITY&useSSL=true&enabledTLSProtocols=TLSv1.2,TLSv1.3&rewriteBatchedStatements=true}
spring.datasource.username=${DB_USERNAME:2vSVQivf8sNBrwn.root}
spring.datasource.password=${DB_PASSWORD:MAT_KHAU_CUA_BAN}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}